### ISSUE TITLE
Should Opts structs fields be exported ?

### ISSUE THREAD

**Issue by ibrierley** [petar-dambovaliev/aho-corasick#1]
Hi, thanks for the work on this. I'm having a few issues with the Opts struct (I'm relatively new to Go). I seem to get an exported issue with it, so wondering if the fields should be in caps ?

**Comment by petar-dambovaliev** [comment]
> Hi, thanks for the work on this. I'm having a few issues with the Opts struct (I'm relatively new to Go). I seem to get an exported issue with it, so wondering if the fields should be in caps ?

Yea, already did it. Thanks for the issue.
I've been working on this for 2 days only.
Please, report if you see any problems.

**Comment by ibrierley** [comment]
Works great, thanks for all of the help.

Ian
