### ISSUE TITLE
Provide methods that accept `[]byte`.

### ISSUE THREAD

**Issue by jeschkies** [petar-dambovaliev/aho-corasick#6]
Hi,

I really like the implementation but would love to have a `FindAll(haystack []byte)` and also a `Build(patterns [][]byte)`. I saw that all patterns and haystacks are converted to `[]byte` internally. What do you think about accepting `[]byte` by default and have the `string` methods call these? E.g. `FindAllByte(haystack []byte)` and then `FindAll(haystack string) { FindAllByte([]byte(haystack)) }`.

**Comment by petar-dambovaliev** [comment]
Hey @jeschkies, thanks for the suggestion. It does make sense.
I am open to contributions. Would you like to make the API nicer?

**Comment by jeschkies** [comment]
Sure. That was quick :slightly_smiling_face:
